services:
  - type: web
    name: web-gift
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
